version: "3.8"
services:
  nginx_shoora:
    image: nginx
    volumes:
      - './nginx/default.conf:/etc/nginx/nginx.conf'
      - './nginx/ssl:/etc/nginx/ssl'
    ports:
      - '8080:80' #local:docker
      - '553:443'
    depends_on:
      - auth-shoora

  #django app
  auth-shoora:
    image: python:3.7
    volumes:
      - ./auth:/app
    command: |
      sh -c '
      cd /app
      pip install --upgrade pip
      make deps
      make migrate
      python manage.py collectstatic
      python manage.py runserver 0.0.0.0:8000
      '
    ports:
      - "8000:8000"
