# Generated by Django 4.1.3 on 2022-12-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_vehicle_organization'),
        ('driver', '0002_driver_organization'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DriveHistory',
            new_name='DriverHistory',
        ),
    ]
