# Generated by Django 4.1.3 on 2022-12-20 10:02

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_vehicle_organization'),
        ('driver', '0003_alter_driver_vehicle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DriveHistory',
            new_name='DriverHistory',
        ),
        migrations.AlterField(
            model_name='driver',
            name='driving_license_validity',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date.today)]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='passport_validity',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date.today)]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
