# Generated by Django 4.1.3 on 2022-12-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_alter_driver_driving_license_validity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
