# Generated by Django 3.2.16 on 2022-12-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0005_auto_20221225_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_score',
            field=models.IntegerField(default=100),
        ),
    ]
