# Generated by Django 4.1.3 on 2022-12-13 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0005_alter_driver_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='driver_score',
        ),
    ]
