# Generated by Django 4.1.3 on 2022-12-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0006_remove_driver_driver_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_score',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
    ]
