# Generated by Django 3.2.16 on 2022-11-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='location',
        ),
        migrations.AddField(
            model_name='alert',
            name='direction',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='latitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='longitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
