# Generated by Django 3.2.16 on 2022-12-02 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alert", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="realtimedatabase",
            old_name="createdAt",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="realtimedatabase",
            old_name="updatedAt",
            new_name="updated_at",
        ),
    ]
