# Generated by Django 3.2.16 on 2022-11-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alert", "0002_auto_20221114_1443"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="identifier",
            field=models.CharField(max_length=50),
        ),
    ]
