# Generated by Django 3.2.16 on 2022-12-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0004_alter_realtimedatabase_terminal_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id_no', models.CharField(max_length=50)),
                ('alert_latitude', models.IntegerField(blank=True, null=True)),
                ('alert_longitude', models.IntegerField(blank=True, null=True)),
                ('alert_description', models.CharField(blank=True, max_length=100, null=True)),
                ('alert_guid', models.CharField(blank=True, max_length=100, null=True)),
                ('hd', models.CharField(max_length=10)),
                ('info', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('p1', models.CharField(max_length=10)),
                ('p2', models.CharField(max_length=10)),
                ('p3', models.CharField(max_length=10)),
                ('p4', models.CharField(max_length=10)),
                ('rve', models.CharField(max_length=10)),
                ('alarm_type_1', models.CharField(max_length=10)),
                ('src_tm', models.CharField(max_length=50)),
                ('alarm_type_2', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=50)),
                ('alert_type_3', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
