# Generated by Django 3.2.16 on 2022-11-14 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('alert', '0004_alert_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
    ]
