# Generated by Django 3.2.16 on 2022-11-16 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
        ("alert", "0005_alert_organization"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Alert",
            new_name="RealTimeDatabase",
        ),
    ]
