# Generated by Django 3.2.16 on 2022-12-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0006_auto_20221210_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawalert',
            name='alert_latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rawalert',
            name='alert_longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
