# Generated by Django 3.2.16 on 2022-11-27 12:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("alert", "0007_alter_realtimedatabase_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realtimedatabase",
            name="uuid",
        ),
        migrations.AlterField(
            model_name="realtimedatabase",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
