# Generated by Django 3.2.16 on 2022-12-11 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_vehicle_organization'),
        ('alert', '0007_auto_20221210_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle'),
        ),
    ]
