# Generated by Django 3.2.16 on 2022-11-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alert", "0008_auto_20221127_1226"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realtimedatabase",
            name="identifier",
        ),
        migrations.RemoveField(
            model_name="realtimedatabase",
            name="organization",
        ),
    ]
