# Generated by Django 3.2.16 on 2022-12-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0008_alert_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alarm_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Alarm Name'),
        ),
        migrations.AddField(
            model_name='alert',
            name='guid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
