# Generated by Django 3.2.16 on 2022-12-17 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_organization_contact_number'),
        ('alert', '0009_auto_20221211_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
        ),
    ]
