# Generated by Django 3.2.16 on 2022-11-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alert", "0010_remove_realtimedatabase_direction"),
    ]

    operations = [
        migrations.AddField(
            model_name="realtimedatabase",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="realtimedatabase",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
