# Generated by Django 3.2.16 on 2022-12-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0010_alert_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimedatabase',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='realtimedatabase',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
