# Generated by Django 3.2.16 on 2022-11-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alert", "0011_auto_20221127_1231"),
    ]

    operations = [
        migrations.RenameField(
            model_name="realtimedatabase",
            old_name="created_at",
            new_name="createdAt",
        ),
        migrations.RenameField(
            model_name="realtimedatabase",
            old_name="updated_at",
            new_name="updatedAt",
        ),
    ]
