# Generated by Django 3.2.16 on 2022-12-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0011_auto_20221217_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimedatabase',
            name='message_serial_number',
            field=models.CharField(max_length=20),
        ),
    ]
