# Generated by Django 3.2.16 on 2022-12-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0013_realtimedatabase_is_corrupt'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimedatabase',
            name='raw_hex_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
