# Generated by Django 3.2.16 on 2022-12-22 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_rename_drivehistory_driverhistory_and_more'),
        ('alert', '0014_realtimedatabase_raw_hex_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.driver'),
        ),
    ]
