# Generated by Django 3.2.16 on 2023-01-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0017_alert_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='device_time',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
