# Generated by Django 3.2.16 on 2023-01-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0018_alert_device_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='device_time',
        ),
        migrations.AddField(
            model_name='realtimedatabase',
            name='device_time',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
