# Generated by Django 3.2.16 on 2023-01-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0024_remove_realtimedatabase_alert_realt_organiz_d83d74_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='realtimedatabase',
            index=models.Index(fields=['organization'], name='alert_realt_organiz_d83d74_idx'),
        ),
    ]
