# Generated by Django 3.2.16 on 2023-01-11 19:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_vehiclegeofence_alert_type'),
        ('device', '0010_device_branch'),
        ('alert', '0027_alter_latestgps_imei'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoFenceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('alert_type', models.CharField(choices=[('IN_ALERT', 'in'), ('OUT_ALERT', 'out'), ('BOTH', 'both')], max_length=10, verbose_name='Geofence Alert')),
                ('latitude', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_alerts', to='device.device')),
                ('geofence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_alerts', to='vehicle.geofence')),
            ],
        ),
    ]
