deps:
	pip install -r requirements.txt

migrations:
	python manage.py makemigrations

migrate:
	python manage.py migrate

run:
	python manage.py runserver

shell:
	python manage.py shell

startapp: 
	python manage.py startapp "$(app)"