# Generated by Django 4.1.3 on 2022-12-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_vehicle_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='last_status_update',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
