# Generated by Django 3.2.16 on 2022-12-29 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20221228_1522'),
        ('vehicle', '0003_alter_vehicle_last_status_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='organization.organization'),
        ),
    ]
