# Generated by Django 3.2.16 on 2023-01-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_geofence_vehiclegeofence_vehiclegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='geofence',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
