# Generated by Django 3.2.16 on 2023-01-06 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_branch'),
        ('vehicle', '0008_auto_20230106_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='organization.branch'),
        ),
    ]
