# Generated by Django 3.2.16 on 2023-01-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_vehicle_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclegeofence',
            name='alert_type',
            field=models.CharField(blank=True, choices=[('IN_ALERT', 'in'), ('OUT_ALERT', 'out'), ('BOTH', 'both')], max_length=10, null=True, verbose_name='Geofence Alert'),
        ),
    ]
