# Generated by Django 3.2.16 on 2022-10-23 19:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('action', models.CharField(max_length=50)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feature.feature', verbose_name='feature')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.role', verbose_name='role')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='user.Role'),
        ),
    ]
