# Generated by Django 3.2.16 on 2022-11-01 17:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Method",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name="accesscontrol",
            name="action",
        ),
        migrations.AddField(
            model_name="accesscontrol",
            name="method",
            field=models.ManyToManyField(
                related_name="access_controls", to="user.Method"
            ),
        ),
    ]
