# Generated by Django 3.2.16 on 2022-11-10 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_auto_20221101_1755"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="display_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
