# Generated by Django 3.2.16 on 2022-11-27 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_user_contact_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Installer",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user.user",),
        ),
    ]
