# Generated by Django 3.2.16 on 2022-12-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20221128_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.PositiveBigIntegerField(),
        ),
    ]
