# Generated by Django 4.1.3 on 2022-12-20 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_contact_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contact_code',
            new_name='country_code',
        ),
    ]
