# Generated by Django 4.1.3 on 2022-12-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_contact_code_user_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
