# Generated by Django 4.1.3 on 2022-12-12 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_rename_country_code_user_contact_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contact_code',
            new_name='country_code',
        ),
    ]
