# Generated by Django 3.2.16 on 2022-11-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="chinese_server_password",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="chinese_server_username",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
