# Generated by Django 3.2.16 on 2022-12-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20221122_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='contact_number',
            field=models.PositiveBigIntegerField(max_length=20),
        ),
    ]
