# Generated by Django 4.1.3 on 2022-12-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_organization_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='contact_code',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='registration_number',
        ),
        migrations.AddField(
            model_name='organization',
            name='country_code',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
