# Generated by Django 4.1.3 on 2022-12-20 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_organization_contact_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='contact_code',
            new_name='country_code',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='registration_number',
        ),
    ]
