# Generated by Django 3.2.16 on 2022-12-17 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_alter_driver_vehicle'),
        ('trip', '0002_auto_20221217_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.driver'),
        ),
    ]
