# Generated by Django 3.2.16 on 2022-12-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_alter_trips_driver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trips',
            options={'verbose_name_plural': 'Trips'},
        ),
    ]
