# Generated by Django 3.2.16 on 2022-11-22 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="device",
            old_name="orgnaization",
            new_name="organization",
        ),
    ]
