# Generated by Django 3.2.16 on 2022-12-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_rename_orgnaization_device_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='sim_number',
            field=models.PositiveBigIntegerField(),
        ),
    ]
