# Generated by Django 3.2.16 on 2022-12-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_alter_device_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='imei_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
